package edu.chalmers.vaporwave.assetcontainer;

public enum ImageID {

    // todo: MENU STUFF

    // backrounds
    MENU_BACKGROUND_1,

    // buttons
    BUTTON_SINGLEPLAYER, BUTTON_EXIT,

    // misc
    MENU_BUTTON_SPRITESHEET,

    MENU_CHARACTER,
    MENU_CHARACTER_SELECTOR,
    MENU_CHECKBOX,

    MENU_ROOSTER_SELECT,

    // todo: GAME STUFF

    // HUD
//    HUD_BOX, HUD_HEALTHBAR_FILLED, HUD_STATUSBAR_FILLED, HUD_STATUSBAR_PLUS,
    HUD_BOX_SHEET, HUD_TIMER_MESSAGE, HUD_GAMEOVER_MESSAGE,
    SCOREBOARD_BACK,

    // gamebackground stuff
    BACKGROUND_PATTERN_1, GAME_BACKGROUND_1, GAME_FRAME_NORTH_1, GAME_FRAME_WEST_1, GAME_FRAME_EAST_1, GAME_FRAME_SOUTH_1,

    // game tiles
    BOMBS_EXPLOSIONS, WALLS, POWERUPS,

    // game characters
    CHARACTER_MISC,
    CHARACTER_ALYSSA_WALKIDLEFLINCH, CHARACTER_ALYSSA_SPAWN, CHARACTER_ALYSSA_DEATH,
    CHARACTER_CHARLOTTE_WALKIDLEFLINCH, CHARACTER_CHARLOTTE_SPAWN, CHARACTER_CHARLOTTE_DEATH,
    CHARACTER_ZYPHER_WALKIDLEFLINCH, CHARACTER_ZYPHER_SPAWN, CHARACTER_ZYPHER_DEATH,
    CHARACTER_MEI_WALKIDLEFLINCHDEATH, CHARACTER_MEI_SPAWN,

    // enemies
    ENEMY_PCCHAN
}
