package edu.chalmers.vaporwave.assetcontainer;

/**
 * An ID for every image to load.
 */
public enum ImageID {

    // backgrounds
    MENU_BACKGROUND_1,
    MENU_BACKGROUND_RESULT,
    MENU_BACKGROUND_CHARACTERSELECT,
    MENU_BACKGROUND_ROOSTER,
    MENU_BACKGROUND_START,
    MENU_BACKGROUND_LOADING,

    // misc
    MENU_BUTTON_SPRITESHEET,
    MENU_SMALL_BUTTON_SPRITESHEET,
    MENU_RESULTS_ZYPHER,
    MENU_RESULTS_CHARLOTTE,
    MENU_RESULTS_MEI,
    MENU_RESULTS_ALYSSA,
    MENU_CHARACTERSELECT_ZYPHER,
    MENU_CHARACTERSELECT_CHARLOTTE,
    MENU_CHARACTERSELECT_MEI,
    MENU_CHARACTERSELECT_ALYSSA,
    MENU_TITLE,
    MENU_ALLCHARACTERS,

    MENU_CHARACTERSELECT_HELP,
    MENU_STARTMENU_HELP,
    MENU_ROOSTER_HELP,

    MENU_CHARACTER,
    MENU_CHARACTER_SELECTOR,
    MENU_CHECKBOX,

    MENU_ROOSTER_SELECT,

    MENU_PAUSE,

    // Hud
    HUD_BOX_SHEET, HUD_TIMER_MESSAGE, HUD_GAMEOVER_MESSAGE,
    SCOREBOARD_BACK,

    // gamebackground stuff
    BACKGROUND_PATTERN_1, GAME_BACKGROUND_1, GAME_FRAME_NORTH_1, GAME_FRAME_WEST_1, GAME_FRAME_EAST_1, GAME_FRAME_SOUTH_1,

    // game tiles
    BOMBS_EXPLOSIONS, WALLS, POWERUPS,

    // game characters
    CHARACTER_MISC,
    CHARACTER_ALYSSA_WALKIDLEFLINCH, CHARACTER_ALYSSA_SPAWN, CHARACTER_ALYSSA_DEATH,
    CHARACTER_CHARLOTTE_WALKIDLEFLINCH, CHARACTER_CHARLOTTE_SPAWN, CHARACTER_CHARLOTTE_DEATH,
    CHARACTER_ZYPHER_WALKIDLEFLINCH, CHARACTER_ZYPHER_SPAWN, CHARACTER_ZYPHER_DEATH,
    CHARACTER_MEI_WALKIDLEFLINCHDEATH, CHARACTER_MEI_SPAWN,

    // enemies
    ENEMY_PCCHAN,

    //fish
    FISH
}
