package edu.chalmers.vaporwave.assetcontainer;

public enum SoundID {
    PLACE_BOMB, EXPLOSION, GAME_MUSIC, POWERUP, CHARACTER_FLINCH,

    //menu
    MENU_FORWARD_CLICK, MENU_BACKWARD_CLICK, MENU_STARTUP, MENU_EXIT,
    MENU_SUCCESS,

    // speech
    MENU_ALYSSA, MENU_CHARLOTTE, MENU_ZYPHER,MENU_MEI, MENU_BGM_1,
    START_GAME, SELECT_CHARACTER, TIME_UP
}
