package edu.chalmers.vaporwave.assetcontainer;

public enum SpriteID {

    // todo: MENU STUFF

    // backrounds
    MENU_BACKGROUND_1,

    // buttons
    BUTTON_SINGLEPLAYER, BUTTON_EXIT,

    // misc
    MENU_CHARACTER_SELECT,

    // todo: GAME STUFF

    // HUD
    HUD_HEALTHBAR_EMPTY, HUD_HEALTHBAR_FILLED, HUD_SCOREBAR_EMPTY, HUD_SCOREBAR_FILLED,
    SCOREBOARD_BACK,

    // gamebackground stuff
    BACKGROUND_PATTERN_1, GAME_BACKGROUND_1, GAME_FRAME_NORTH_1, GAME_FRAME_WEST_1, GAME_FRAME_EAST_1, GAME_FRAME_SOUTH_1,

    // game tiles
    BOMB_ALYSSA, BOMB_CHARLOTTE, BOMB_ZYPHER, BOMB_MEI, MINE,
    BLAST_CENTER, BLAST_BEAM_NORTH, BLAST_BEAM_WEST, BLAST_BEAM_EAST, BLAST_BEAM_SOUTH,
    BLAST_END_NORTH, BLAST_END_WEST, BLAST_END_EAST, BLAST_END_SOUTH,
    WALL_DESTR_PARASOL, WALL_DESTR_PARASOL_DESTROYED, WALL_INDESTR_BEACHSTONE,

    POWERUP_HEALTH, POWERUP_BOMBCOUNT, POWERUP_RANGE, POWERUP_SPEED,
    POWERUP_HEALTH_SPAWN, POWERUP_BOMBCOUNT_SPAWN, POWERUP_RANGE_SPAWN, POWERUP_SPEED_SPAWN,
    POWERUP_HEALTH_PICKUP, POWERUP_BOMBCOUNT_PICKUP, POWERUP_RANGE_PICKUP, POWERUP_SPEED_PICKUP,
    POWERUP_HEALTH_DESTROY, POWERUP_BOMBCOUNT_DESTROY, POWERUP_RANGE_DESTROY, POWERUP_SPEED_DESTROY,

    // game characters
    CHARACTER_MISC,
    CHARACTER_ALYSSA_WALKIDLEFLINCH, CHARACTER_ALYSSA_SPAWN, CHARACTER_ALYSSA_DEATH,
    CHARACTER_CHARLOTTE_WALKIDLEFLINCH, CHARACTER_CHARLOTTE_SPAWN, CHARACTER_CHARLOTTE_DEATH,
    CHARACTER_ZYPHER_WALKIDLEFLINCH, CHARACTER_ZYPHER_SPAWN, CHARACTER_ZYPHER_DEATH,
    CHARACTER_MEI_WALKIDLEFLINCH, CHARACTER_MEI_SPAWN, CHARACTER_MEI_DEATH,

    // enemies
    ENEMY_PCCHAN
}
