package edu.chalmers.vaporwave.assetcontainer;

/**
 * An ID for every sprite to create.
 */
public enum SpriteID {

    // --- MENU

    // Start menu
    MENU_TITLE,
    MENU_ALLCHARACTERS,

    // Character select
    MENU_CHARACTER_ALL,
    MENU_CHARACTER_MEI_1,
    MENU_CHARACTER_ALYSSA_1,
    MENU_CHARACTER_ZYPHER_1,
    MENU_CHARACTER_CHARLOTTE_1,
    MENU_CHARACTER_MEI_2,
    MENU_CHARACTER_ALYSSA_2,
    MENU_CHARACTER_ZYPHER_2,
    MENU_CHARACTER_CHARLOTTE_2,
    MENU_CHARACTER_MEI_3,
    MENU_CHARACTER_ALYSSA_3,
    MENU_CHARACTER_ZYPHER_3,
    MENU_CHARACTER_CHARLOTTE_3,
    MENU_CHARACTER_MEI_4,
    MENU_CHARACTER_ALYSSA_4,
    MENU_CHARACTER_ZYPHER_4,
    MENU_CHARACTER_CHARLOTTE_4,

    MENU_CHARACTERSELECT_ZYPHER,
    MENU_CHARACTERSELECT_CHARLOTTE,
    MENU_CHARACTERSELECT_MEI,
    MENU_CHARACTERSELECT_ALYSSA,

    MENU_SIGN_ALYSSA,
    MENU_SIGN_CHARLOTTE,
    MENU_SIGN_MEI,
    MENU_SIGN_ZYPHER,

    MENU_CHARACTER_SELECTOR_1,
    MENU_CHARACTER_SELECTOR_2,
    MENU_CHARACTER_SELECTOR_3,
    MENU_CHARACTER_SELECTOR_4,

    // Rooster menu
    MENU_ROOSTER_SELECT_OPEN_OFF,
    MENU_ROOSTER_SELECT_P1_OFF,
    MENU_ROOSTER_SELECT_P2_OFF,
    MENU_ROOSTER_SELECT_P3_OFF,
    MENU_ROOSTER_SELECT_P4_OFF,
    MENU_ROOSTER_SELECT_CPU_OFF,
    MENU_ROOSTER_SELECT_OPEN_ON,
    MENU_ROOSTER_SELECT_P1_ON,
    MENU_ROOSTER_SELECT_P2_ON,
    MENU_ROOSTER_SELECT_P3_ON,
    MENU_ROOSTER_SELECT_P4_ON,
    MENU_ROOSTER_SELECT_CPU_ON,

    // Result menu
    MENU_RESULTS_ZYPHER,
    MENU_RESULTS_CHARLOTTE,
    MENU_RESULTS_MEI,
    MENU_RESULTS_ALYSSA,

    // Map select
    MENU_MAPSELECT_MARK,
    MENU_MAPSELECT_DESTRUCTIBLE,
    MENU_MAPSELECT_INDESTRUCTIBLE,

    MENU_MAPSELECT_ARROW_LEFT,
    MENU_MAPSELECT_ARROW_RIGHT,

    // Misc
    MENU_CHARACTERSELECT_HELP,
    MENU_STARTMENU_HELP,
    MENU_ROOSTER_HELP,

    MENU_CHECKBOX_UNSELECTED_OFF,
    MENU_CHECKBOX_UNSELECTED_ON,
    MENU_CHECKBOX_SELECTED_OFF,
    MENU_CHECKBOX_SELECTED_ON,


    // --- GAME

    // HUD
    HUD_BOX, HUD_HEALTHBAR_FILLED, HUD_STATUSBAR_FILLED, HUD_STATUSBAR_PLUS,
    HUD_TIMER_MESSAGE, HUD_GAMEOVER_MESSAGE,
    SCOREBOARD_BACKGROUND, MENU_PAUSE,

    // Backgrounds
    GAME_BACKGROUND_1, GAME_FRAME_NORTH_1, GAME_FRAME_WEST_1, GAME_FRAME_EAST_1, GAME_FRAME_SOUTH_1,

    // Tiles
    BOMB_ALYSSA, BOMB_CHARLOTTE, BOMB_ZYPHER, BOMB_MEI, MINE,
    BLAST_CENTER, BLAST_BEAM_NORTH, BLAST_BEAM_WEST, BLAST_BEAM_EAST, BLAST_BEAM_SOUTH,
    BLAST_END_NORTH, BLAST_END_WEST, BLAST_END_EAST, BLAST_END_SOUTH,
    WALL_DESTR_PARASOL, WALL_DESTR_PARASOL_DESTROYED, WALL_INDESTR_BEACHSTONE,

    // Powerups
    POWERUP_HEALTH, POWERUP_BOMBCOUNT, POWERUP_RANGE, POWERUP_SPEED,
    POWERUP_HEALTH_SPAWN, POWERUP_BOMBCOUNT_SPAWN, POWERUP_RANGE_SPAWN, POWERUP_SPEED_SPAWN,
    POWERUP_HEALTH_PICKUP, POWERUP_BOMBCOUNT_PICKUP, POWERUP_RANGE_PICKUP, POWERUP_SPEED_PICKUP,
    POWERUP_HEALTH_DESTROY, POWERUP_BOMBCOUNT_DESTROY, POWERUP_RANGE_DESTROY, POWERUP_SPEED_DESTROY,

    POWERUP_SPARKLES,

    // FISH
    FISH
}
