package edu.chalmers.vaporwave.util;

public enum ImageID {
    CHARACTER_MISC, BACKGROUND_PATTERN_1, GAME_BACKGROUND_1, GAME_FRAME_NORTH_1, GAME_FRAME_WEST_1, GAME_FRAME_EAST_1,
    GAME_FRAME_SOUTH_1, BOMBS_EXPLOSIONS, WALLS, POWERUPS
}
